---
# tasks file for registry

- name: Registry Storage Directory
  file:
    path: /data
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Registry Certs Directory
  file:
    path: /certs
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Docker Registry Container
  docker:
    name: registry
    image: registry:2
    state: started
    restart_policy: always
    env:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/rococo_io.crt
      REGISTRY_HTTP_TLS_KEY: /certs/rococo_io.key
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      - /data:/var/lib/registry
      - /certs:/certs
    ports:
      - 5000:5000
